# Virana Cultural Calendar — 2026 festival dataset.
# Dates verified against Drik Panchang / standard panchang sources (lunar festivals shift yearly).
BASE = "https://static.prod-images.emergentagent.com/jobs/f4c46e26-5f92-4e0f-a80a-c173853e8734/images/"
IMG = {
    "makar_sankranti": "d0614e033da8009cb63c23911b97fce3ee3489d0c21ecf1c511f721ac4bacf25",
    "pongal": "eb5b5872d9598df1921a7e2bba4be3acd24c05c1ad7f15e5fd660be985ba1d96",
    "lohri": "fbc91e9b66649465963c79b9a182b78dab070574cae264b30e05096ab759407e",
    "magh_bihu": "ac1e357dc6bda5f48bcb0953744eb08d5e9bba965f7a887d8207eaa23099430f",
    "vasant_panchami": "e922e37313e44248472323b34d769314645574ed19cff389b70ba5b52c605e8f",
    "maha_shivaratri": "ae3c286dea8c3f0f3fdabaa579849f5fdd1435cec9f000d07625d8296a79a25d",
    "losar": "35d8000f582bc6dfc277373cd6c6b9ca16f367dd7ed9d6b37bab0cda10ea5ff8",
    "holi": "99761208f39d86de1028b0a99753198a2d34f7071aaa24ee2c77a68ac1565b0a",
    "chapchar_kut": "eac4f80efc05e34fb443e234dc804f1402e2576f8d36d279b3cc3219423a1a81",
    "ugadi": "4e1627f7492f379653628dd5f1fe57eb205f8fc4611b85fc39d4e082ddd7d32e",
    "gudi_padwa": "f71241c2d59c8be60e067796e9fa94175f6bebade1b04b8c4ae475eb6b2ff042",
    "ram_navami": "3019fbc5b2a1fcaabb48794b313ab3590b2b12d362d437629a89f91319139c8f",
    "baisakhi": "41b90103abded8b47b1b60fd55494e986f111930a40d3b01a4feae0eceb81b91",
    "vishu": "cc371d60d26b329a85c58b457281e9559d2d4b936e85622a427165b7aa5882aa",
    "bohag_bihu": "60034143156fef671b258968e24f5713b37f2d0e483eae8439f72fce796e049e",
    "buddha_purnima": "28fe3c7ae6e8b36b212f29f0198e26788a09824b81e455c7f1892e7b6d684c41",
    "thrissur_pooram": "3d036254b432ffd65c1944a82d211aa26f8e76d2f0b359f0e9e04e9774c9222e",
    "hemis_festival": "0d3a2722cc75cab247d51ee0c619337cd0ad0d2a9a7837d9020ac604f51b9941",
    "rath_yatra": "3bada8dc0678d90651909f83a7b581f52054791e9999cb6045325053b0f7e705",
    "guru_purnima": "bc76f690d48d411f3d1a069305bab8fcdb75382997c00f373e617d89bf73ad9b",
    "bonalu": "1d3b2f4daa870489ede84b1afb3f5f968064779050bd3a667f6fbe3fcc536380",
    "ashadhi_ekadashi": "14fb0c56cfc446072a797c79da02a92b85fec302aa6943a895be1cef10bf70d5",
    "onam": "fa389bdc7bcb8318bc4ac9b9a60da13c2bc4cb41cfe2d9201f927f7f89ea5636",
    "janmashtami": "fc09ad5183e22cf1443df00ada4e972673f8261f6aa3f9de8feab11d656b76e3",
    "raksha_bandhan": "1e2c24fe8f98947c78f94e220fe4281646a3d4d0450f5524f7337b8b60dff1ab",
    "ganesh_chaturthi": "326e3cdba0c3185cead8f4530feacc79fdfe9da6c91993cb112bc6972caa2b42",
    "nuakhai": "cf68449610c71598596c62013bcecf110ca2940f4cfccf4acc9a92dbb8fc4dc6",
    "navratri_garba": "4f1dc9e0d1d28527b1878cb8ef3fa311d3edf87cff3806e2c76f2b956d0cbe2a",
    "durga_puja": "3eac70deac4f3cf8411877c46ae3a30577e3ec317abc300291a572fe0454522c",
    "dussehra_ravana": "72db322222979dc620a135cb83603bf3a114233c79ec3c8fb63232202f22983f",
    "mysuru_dasara": "672113693020d233349e10ce5209e151b9260d14cdf6b21a3b517d791a508a38",
    "kullu_dussehra": "66dcfe2ed3253ae9ee1810a01d83069dc702c36b4ff29c938558b0690ee47863",
    "bastar_dussehra": "b458baee5068618c6d1e581152a93d3112a52a51be4564d719b11fb6d16ab7ec",
    "bathukamma": "517226b4a9f803b5939d7c8d3599f770677cf71689f60e8b4ac3264ccd5c94f7",
    "diwali": "dbc58b158879bd4d2a275b4313bff5dc179b229d8c3ceb30a9c0a7e64b192575",
    "chhath_puja": "0002bd29628b11d1811cd39d6f391eb0aac00bb2a4ffc3879b9b93acfba68ac1",
    "guru_nanak_gurpurab": "2a66331e95a475986c985da64054512b1532218746d37a085d8fcb14e906d6f6",
    "hornbill_festival": "3f6a084650c4bb9282e792f159a2f9961aabb9afd898587689296e0f7baff5ca",
    "pushkar_fair": "792eb6681618cb344b1a38173da72e9863dac1ea64cdb3f6bb7d29b931833d14",
    "temple_festival_generic": "011c85845d5dcc2dd156396a9147af852e82163dcb52bccdb5c42cf458d28c69",
    "govardhan_annakut": "628e1739fb175ddde5314184a836e19f94253077db2e4dbd65d145a8e9bc9679",
    "bhai_dooj": "63628997d62cfad2fb71c71896031a1a7cc0dbdc172da8f8c2012bb4e3ccc9fe",
    "christmas_goa": "b6a44abb4f36f773c683139fd6e174a76c6d90fb9e20a425d8c769e8572fc610",
    "republic_day": "84efc6fe7c7a3226cc1f18ba846fabe83f33792d1326467f2b8ad113f9902fe7",
    "mahavir_jayanti": "ce3a17d72e16c27f41c7d98ea22efc1d3f5837bbfc8541e991c32793c1b4f002",
    "harvest_generic": "603b706e64dac76f8fc7dee90fb29c28d0a7e9579ec264147361098921b4af83",
    "ambubachi_mela": "e415c0f81bd5cdb9f805ae7cec198ffae984859778c002990a4f8027e35e4ed7",
    "ziro_music": "37a35a9bf29ec5d816fae786fb3bbf36f95e770c778684c4e0526ab0aebce1db",
}

def img(key):
    return BASE + IMG[key] + ".jpeg"

SRC = "https://www.drikpanchang.com/calendars/indian/indiancalendar.html"
IMG_SOURCE = "AI-generated cultural illustration (Virana Archive)"

def F(id, name, ftype, start, end, region, state, district, lat, lng, image_key, description,
      significance, history="", celebrated="", traditions=None, foods=None, music="", dance="",
      rituals=None, variations=None, related=None, verification="verified", source_url=SRC):
    m_start, m_end = int(start[5:7]), int(end[5:7])
    months = list(range(m_start, m_end + 1)) if m_end >= m_start else list(range(m_start, 13)) + list(range(1, m_end + 1))
    return {
        "id": id, "name": name, "type": ftype,
        "start_date": start, "end_date": end, "months": months,
        "region": region, "state": state, "district": district, "lat": lat, "lng": lng,
        "description": description, "significance": significance, "history": history,
        "celebrated": celebrated, "traditions": traditions or [], "foods": foods or [],
        "music": music, "dance": dance, "rituals": rituals or [],
        "variations": variations or [], "related_heritage": related or [],
        "image": img(image_key), "image_source": IMG_SOURCE, "source_url": source_url,
        "verification": verification, "year": 2026,
    }

FESTIVAL_SEED = [
    # ---------------- JANUARY ----------------
    F("lohri", "Lohri", "harvest", "2026-01-13", "2026-01-13", "North India", "Punjab", "Amritsar", 31.634, 74.872, "lohri",
      "Punjab's winter bonfire festival marking the end of the sowing season and the peak of winter, celebrated on the eve of Makar Sankranti.",
      "Honours Surya and Agni; families circle the bonfire tossing til, gur, popcorn and rewri as thanksgiving for the rabi harvest.",
      "Linked to folk hero Dulla Bhatti, whose ballads are sung around Lohri fires since Mughal times.",
      "Community bonfires at night, folk songs, bhangra and gidda dancing, first-Lohri celebrations for newlyweds and newborns.",
      ["Bonfire offerings of sesame and jaggery", "Dulla Bhatti folk songs", "First Lohri of a bride or newborn"],
      ["Sarson da saag & makki di roti", "Til-gur laddoo", "Gajak", "Rewri"], "Punjabi folk boliyan with dhol", "Bhangra and Gidda",
      ["Circling the bonfire", "Offering til-gur to the fire"], [],
      ["pashmina"]),
    F("makar-sankranti", "Makar Sankranti", "harvest", "2026-01-14", "2026-01-14", "Pan-India", "Pan-India", None, 23.022, 72.571, "makar_sankranti",
      "The great solar transition festival, when the sun enters Makara (Capricorn), celebrated across India under many names with kites, harvest offerings and holy dips.",
      "One of the few solar-calendar Hindu festivals, marking Uttarayana — the sun's northward journey — considered highly auspicious.",
      "Referenced in the Mahabharata; Bhishma chose Uttarayana to leave his body.",
      "Kite flying, sesame-jaggery sweets, holy dips at Ganga Sagar and Prayagraj, cattle worship in the south.",
      ["Kite flying", "Til-gur exchange", "Holy dips in rivers"],
      ["Til laddoo", "Pongal rice", "Khichdi", "Undhiyu"], "Folk songs of the harvest", "",
      ["Surya arghya at dawn"],
      [{"region": "Gujarat", "name": "Uttarayan", "note": "Sky-blackening kite battles over Ahmedabad and Surat."},
       {"region": "Tamil Nadu", "name": "Pongal", "note": "Four-day harvest thanksgiving."},
       {"region": "Assam", "name": "Magh Bihu", "note": "Meji bonfires and feasting."},
       {"region": "Punjab", "name": "Maghi", "note": "Holy dips and remembrance of the Forty Liberated Ones."}],
      ["konark-sun-temple"]),
    F("pongal", "Pongal", "harvest", "2026-01-14", "2026-01-17", "South India", "Tamil Nadu", "Thanjavur", 10.787, 79.137, "pongal",
      "Tamil Nadu's four-day harvest thanksgiving — Bhogi, Thai Pongal, Mattu Pongal and Kaanum Pongal — when the new rice is ceremonially boiled until it overflows.",
      "The overflowing pot of sweet pongal symbolises abundance; 'Thai pirandhal vazhi pirakkum' — the month of Thai opens new paths.",
      "A festival over 1,000 years old, celebrated in Chola inscriptions as Puthiyeedu.",
      "Kolam drawn at dawn, new clay pots boiled with fresh rice, cattle decorated and honoured on Mattu Pongal, jallikattu in some districts.",
      ["Kolam rice-flour art", "Mattu Pongal cattle worship", "Jallikattu bull-taming (regulated)"],
      ["Sakkarai pongal", "Ven pongal", "Sugarcane", "Murukku"], "Nadaswaram and folk melam", "Kummi and Kolattam",
      ["Boiling the first rice at sunrise facing east"], [],
      ["meenakshi-temple", "carnatic-music"]),
    F("magh-bihu", "Magh Bihu (Bhogali Bihu)", "harvest", "2026-01-16", "2026-01-17", "Northeast India", "Assam", "Guwahati", 26.144, 91.736, "magh_bihu",
      "Assam's harvest feast marking the end of the paddy season, centred on Uruka community feasts and the dawn burning of the Meji bonfire.",
      "Bhogali means feasting — granaries are full and the community eats together in bamboo bhelaghars built for the night.",
      "Rooted in ancient Tai-Ahom and indigenous agrarian fire rites.",
      "Night-long Uruka feasts, dawn Meji fires, buffalo and egg fights in some villages, traditional games.",
      ["Bhelaghar night huts", "Meji bonfire at dawn"],
      ["Pitha rice cakes", "Laru", "Doi-chira", "Fish preparations"], "Bihu dhol and pepa", "Bihu naas",
      ["Offering pitha to the Meji flames"], [], []),
    F("vasant-panchami", "Vasant Panchami", "religious", "2026-01-23", "2026-01-23", "North & East India", "West Bengal", "Kolkata", 22.572, 88.363, "vasant_panchami",
      "The festival of Saraswati, goddess of knowledge, music and the arts, marking the first stirring of spring — celebrated in yellow, the colour of mustard fields.",
      "Students place books and instruments before Saraswati; children are initiated into writing (Vidyarambham / Haate Khori).",
      "Celebrated since Gupta-era spring courts as Vasantotsava.",
      "Saraswati puja in homes, schools and pandals; yellow attire; kite flying in Punjab.",
      ["Haate Khori first-writing ceremony", "Yellow garments and offerings"],
      ["Boondi laddoo", "Kesar halwa", "Khichuri bhog"], "Saraswati vandana", "",
      ["Anjali offering of palash flowers"], [], ["sitar", "carnatic-music"]),
    F("republic-day-culture", "Republic Day Cultural Celebrations", "national", "2026-01-26", "2026-01-26", "Pan-India", "Delhi", "New Delhi", 28.613, 77.209, "republic_day",
      "India's Republic Day parade on Kartavya Path is the nation's grandest cultural showcase — state tableaux, folk dance contingents and regiments celebrating the Constitution's adoption in 1950.",
      "A living exhibition of India's federal cultural diversity, with each state presenting its heritage in moving tableaux.",
      "First celebrated on 26 January 1950 when the Constitution came into force.",
      "Parade, tableaux, folk troupes, Beating Retreat on 29 January.",
      ["State tableaux", "Folk dance contingents"], [], "Massed bands", "Folk dances of every state", [], [],
      ["red-fort"]),

    # ---------------- FEBRUARY ----------------
    F("maha-shivaratri", "Maha Shivaratri", "religious", "2026-02-15", "2026-02-15", "Pan-India", "Uttar Pradesh", "Varanasi", 25.311, 83.010, "maha_shivaratri",
      "The Great Night of Shiva — a night-long vigil of fasting, chanting and abhisheka at Shiva temples from Kashi to Chidambaram.",
      "Marks the night Shiva is said to have performed the Tandava and wedded Parvati; devotees keep jaagran through four prahars of worship.",
      "One of the oldest continuously observed Hindu vratas, referenced in the Puranas.",
      "Milk, bel leaves and water offered on the shivalinga through the night; temple fairs at Kashi Vishwanath, Somnath, Srisailam and Pashupatinath.",
      ["Four-prahar abhisheka", "Night vigil (jaagran)", "Rudraksha and vibhuti"],
      ["Vrat foods: sabudana, fruits, thandai"], "Rudram chanting, damaru", "Tandava-themed classical performances",
      ["Bel-patra offering", "Fasting till dawn"],
      [{"region": "Kashmir", "name": "Herath", "note": "Kashmiri Pandit celebration with walnut offerings."},
       {"region": "Andhra Pradesh", "name": "Srisailam Brahmotsavam", "note": "Grand jatara at the Mallikarjuna Jyotirlinga."}],
      ["khajuraho", "meenakshi-temple"]),
    F("losar", "Losar — Himalayan New Year", "cultural", "2026-02-18", "2026-02-20", "Himalayan India", "Ladakh", "Leh", 34.164, 77.584, "losar",
      "The Tibetan-Buddhist New Year of Ladakh, Sikkim and the high Himalaya — monasteries stage masked Cham dances and homes are purified with juniper smoke.",
      "A renewal rite balancing the old year's misfortunes with blessings for the new, rooted in both Bon and Buddhist tradition.",
      "Predates Buddhism in Tibet as a winter incense-offering festival.",
      "Cham dances at monasteries, butter-lamp offerings, guthuk noodle soup, ibex figurines of dough.",
      ["Cham masked dances", "Juniper purification", "Metho torch procession"],
      ["Guthuk soup", "Khapse fried pastries", "Butter tea"], "Monastic horns and cymbals", "Cham",
      ["Torma offerings"], [{"region": "Sikkim", "name": "Sonam Losar", "note": "Tamang and Sherpa new-year variants."}], []),
    F("khajuraho-dance-festival", "Khajuraho Dance Festival", "cultural", "2026-02-20", "2026-02-26", "Central India", "Madhya Pradesh", "Chhatarpur", 24.852, 79.921, "temple_festival_generic",
      "A week of India's greatest classical dancers performing against the floodlit Chandela temples of Khajuraho.",
      "Revives the ancient bond between temple architecture and classical dance; every major style — Bharatanatyam to Kathak — takes the open-air stage.",
      "Instituted in 1975 by Madhya Pradesh's culture department.",
      "Evening open-air recitals before the Western Group of temples.",
      ["Open-air classical recitals"], [], "Live Hindustani & Carnatic ensembles", "All eight classical dance forms", [], [],
      ["khajuraho", "bharatanatyam", "kathakali", "kuchipudi"], "verified",
      "https://www.mptourism.com"),

    # ---------------- MARCH ----------------
    F("holi", "Holi", "religious", "2026-03-03", "2026-03-04", "Pan-India", "Uttar Pradesh", "Mathura", 27.492, 77.673, "holi",
      "India's festival of colours — Holika Dahan bonfires on the eve, then a morning when the whole country dissolves social boundaries in clouds of gulal.",
      "Celebrates the triumph of Prahlada's devotion over Holika, and the playful love of Radha-Krishna in Braj.",
      "Described in ancient texts as Holikotsava; Braj's Lathmar Holi tradition is centuries old.",
      "Holika bonfires, colour play, thandai, community feasting and forgiveness.",
      ["Holika Dahan bonfire", "Gulal colour play", "Lathmar Holi of Barsana"],
      ["Gujiya", "Thandai", "Puran poli", "Malpua"], "Hori and Phag folk songs", "Raslila performances",
      ["Bonfire circumambulation"],
      [{"region": "Braj (UP)", "name": "Lathmar Holi", "note": "Women of Barsana playfully beat men of Nandgaon with staves."},
       {"region": "West Bengal", "name": "Dol Jatra", "note": "Swing festival of Krishna with abir."},
       {"region": "Punjab", "name": "Hola Mohalla", "note": "Nihang martial displays at Anandpur Sahib."}],
      ["holi", "madhubani"]),
    F("chapchar-kut", "Chapchar Kut", "tribal", "2026-03-06", "2026-03-06", "Northeast India", "Mizoram", "Aizawl", 23.727, 92.717, "chapchar_kut",
      "Mizoram's spring festival held after the jhum clearing season, famed for the Cheraw bamboo dance performed in full traditional dress.",
      "A thanksgiving before sowing, uniting Mizo clans in dance, feasting and community games.",
      "Revived in 1962 as the state's flagship cultural celebration.",
      "Mass Cheraw performances at Aizawl's AR grounds, folk sports, traditional attire.",
      ["Cheraw bamboo dance", "Khuallam guest dance"],
      ["Bai vegetable stew", "Zu rice preparations"], "Mizo drums and gongs", "Cheraw",
      [], [], []),
    F("ugadi", "Ugadi", "cultural", "2026-03-19", "2026-03-19", "South India", "Telangana", "Hyderabad", 17.385, 78.486, "ugadi",
      "The lunar New Year of Telangana, Andhra Pradesh and Karnataka, opening the year with mango-leaf torans and the six-taste Ugadi pachadi.",
      "The pachadi of neem, jaggery, tamarind, raw mango, chilli and salt teaches acceptance of all six flavours of life.",
      "From 'Yuga Adi' — the beginning of an age; tied to Chalukya and Vijayanagara new-year courts.",
      "Oil bath at dawn, mango torans, pachadi, Panchanga Sravanam (reading of the new almanac).",
      ["Ugadi pachadi", "Panchanga Sravanam", "Kavi sammelanam poetry"],
      ["Ugadi pachadi", "Bobbatlu", "Pulihora"], "Carnatic kritis", "",
      ["New almanac reading"],
      [{"region": "Karnataka", "name": "Yugadi", "note": "Bevu-bella neem and jaggery exchange."}],
      ["telugu-language", "kuchipudi"]),
    F("gudi-padwa", "Gudi Padwa", "cultural", "2026-03-19", "2026-03-19", "West India", "Maharashtra", "Pune", 18.520, 73.856, "gudi_padwa",
      "The Marathi New Year, when households raise the gudi — a silk-draped staff crowned with an inverted kalash — to welcome victory and prosperity.",
      "The gudi commemorates Shalivahana's victory and Rama's return; it wards off evil from the household.",
      "Anchored to the Shalivahana Shaka calendar begun in 78 CE.",
      "Gudi hoisting at dawn, rangoli, shobha yatra processions in Girgaum with dhol-tasha and lezim.",
      ["Gudi hoisting", "Shobha yatra processions"],
      ["Shrikhand-puri", "Puran poli", "Neem-jaggery prasad"], "Dhol-tasha pathaks", "Lezim",
      [], [], ["warli-art"]),
    F("ram-navami", "Ram Navami", "religious", "2026-03-26", "2026-03-26", "Pan-India", "Uttar Pradesh", "Ayodhya", 26.799, 82.204, "ram_navami",
      "The birth anniversary of Lord Rama, celebrated with Ramayana recitals, temple processions and the great mela at Ayodhya.",
      "Rama embodies dharma; the day closes the Chaitra Navratri with kanya puja and Ram katha.",
      "Ram katha traditions flourished through Valmiki's epic and Tulsidas's Ramcharitmanas.",
      "Akhand path recitals, Ram baraat processions, panakam and neer mor offerings in the south.",
      ["Ramayana parayana", "Ram baraat processions"],
      ["Panakam", "Kosambari", "Dhaniya panjiri"], "Ram bhajans", "Ramlila excerpts",
      ["Midday birth-moment aarti"],
      [{"region": "South India", "name": "Sri Rama Navami Kalyanam", "note": "Ceremonial wedding of Rama and Sita at Bhadrachalam."}],
      []),
    F("mahavir-jayanti", "Mahavir Jayanti", "religious", "2026-03-31", "2026-03-31", "Pan-India", "Rajasthan", "Pali (Ranakpur)", 25.116, 73.473, "mahavir_jayanti",
      "The birth anniversary of Bhagwan Mahavira, the 24th Tirthankara, observed by the Jain community with abhisheka, processions and acts of charity.",
      "A day dedicated to ahimsa (non-violence), truth and compassion — Mahavira's core teachings.",
      "Mahavira was born in 599 BCE at Kshatriyakund, Bihar.",
      "Rath yatras with the Tirthankara image, temple abhisheka, charity to gaushalas, lectures on ahimsa.",
      ["Abhisheka of Tirthankara idols", "Ahimsa processions"],
      ["Sattvik Jain feast (no root vegetables)"], "Jain stavans", "", [], [], []),

    # ---------------- APRIL ----------------
    F("baisakhi", "Baisakhi", "harvest", "2026-04-14", "2026-04-14", "North India", "Punjab", "Amritsar", 31.634, 74.872, "baisakhi",
      "Punjab's harvest new year and the founding day of the Khalsa — golden wheat fields, bhangra, and nagar kirtans from Anandpur Sahib to Amritsar.",
      "On Baisakhi 1699 Guru Gobind Singh founded the Khalsa Panth, making the day both agrarian thanksgiving and a Sikh landmark.",
      "The rabi wheat harvest festival of the Punjab plains for centuries.",
      "Gurdwara kirtans and langar, bhangra in the fields, Baisakhi melas.",
      ["Nagar kirtan", "Langar community kitchen", "Harvest fairs"],
      ["Kada prasad", "Langar dal-roti", "Lassi"], "Dhol and boliyan", "Bhangra and Gidda",
      [], [{"region": "Kerala", "name": "Vishu", "note": "Malayali new year on the same solar transition."},
           {"region": "Tamil Nadu", "name": "Puthandu", "note": "Tamil new year."},
           {"region": "Bengal", "name": "Poila Boishakh", "note": "Bengali new year."}],
      []),
    F("vishu", "Vishu", "cultural", "2026-04-15", "2026-04-15", "South India", "Kerala", "Ernakulam", 9.931, 76.267, "vishu",
      "Kerala's astronomical new year, greeted at dawn by the Vishu Kani — an arrangement of golden konna flowers, rice, fruit and a mirror seen as the year's first sight.",
      "The first sight (kani) of auspicious abundance is believed to shape the whole year; elders gift kaineettam coins to the young.",
      "A Malayali solar new-year rite recorded from the medieval period.",
      "Kani viewing before dawn, kaineettam gifting, sadya feast, temple visits to Guruvayur and Sabarimala.",
      ["Vishu Kani arrangement", "Kaineettam coin gifting"],
      ["Vishu sadya", "Vishu katta", "Mampazha pulissery"], "Sopana sangeetham", "",
      ["Blindfolded walk to the kani at dawn"], [], ["kathakali", "kavu-groves", "malabar-spices"]),
    F("puthandu", "Puthandu — Tamil New Year", "cultural", "2026-04-14", "2026-04-14", "South India", "Tamil Nadu", "Madurai", 9.925, 78.119, "ugadi",
      "The Tamil New Year, welcomed with kolam, mango-neem pachadi and the first glance at auspicious things arranged the night before (kanni).",
      "The maanga pachadi of sweet, sour and bitter flavours mirrors the year ahead — a philosophy shared with Ugadi.",
      "Anchored to the Tamil solar calendar month of Chithirai; Madurai's Chithirai festival follows.",
      "Kanni viewing, new clothes, temple visits, family feasts.",
      ["Kanni auspicious viewing", "Kolam"],
      ["Maanga pachadi", "Vadai", "Payasam"], "Nadaswaram", "",
      [], [], ["meenakshi-temple"]),
    F("bohag-bihu", "Bohag Bihu (Rongali Bihu)", "harvest", "2026-04-14", "2026-04-16", "Northeast India", "Assam", "Jorhat", 26.757, 94.203, "bohag_bihu",
      "Assam's joyous spring new year — seven days of Bihu dance, dhol and pepa, cattle bathing and husori house-to-house singing.",
      "Rongali means rejoicing; it opens the Assamese agricultural year with courtship dances in the open fields.",
      "An ancient agrarian fertility festival of the Brahmaputra valley.",
      "Goru Bihu cattle washing, Bihu naas in fields and stages, gamosa gifting.",
      ["Husori troupes", "Gamosa gifting", "Goru Bihu"],
      ["Pitha", "Laru", "Curd and chira"], "Dhol, pepa, gogona", "Bihu dance",
      [], [], []),
    F("poila-boishakh", "Poila Boishakh", "cultural", "2026-04-15", "2026-04-15", "East India", "West Bengal", "Kolkata", 22.572, 88.363, "harvest_generic",
      "The Bengali New Year — traders open fresh haal khata ledgers, homes draw alpona, and Kolkata rings in Noboborsho with Rabindra sangeet processions.",
      "A cultural (not religious) new year uniting Bengalis across faiths, tied to the Bengali solar calendar.",
      "Formalised under Akbar's land-revenue calendar reforms.",
      "Haal khata ledger ceremonies, prabhat pheri processions, new clothes and sweets.",
      ["Haal khata", "Alpona floor art", "Prabhat pheri"],
      ["Panta bhat", "Mishti doi", "Rosogolla"], "Rabindra sangeet", "",
      [], [], []),
    F("thrissur-pooram", "Thrissur Pooram", "religious", "2026-04-26", "2026-04-26", "South India", "Kerala", "Thrissur", 10.527, 76.214, "thrissur_pooram",
      "Kerala's grandest temple festival — thirty caparisoned elephants, the kudamattam parasol exchange and a percussion ocean of panchavadyam before Vadakkunnathan temple.",
      "A meeting of ten temples arranged in the 18th century as a spectacle of devotion open to all communities.",
      "Instituted by Sakthan Thampuran, Raja of Cochin, around 1798.",
      "Elephant processions, ilanjithara melam of 250 percussionists, fireworks at dawn.",
      ["Kudamattam parasol exchange", "Ilanjithara melam", "Nettipattam elephant regalia"],
      ["Kerala sadya"], "Panchavadyam & chenda melam", "",
      [], [], ["kathakali", "kavu-groves"]),

    # ---------------- MAY / JUNE ----------------
    F("buddha-purnima", "Buddha Purnima", "religious", "2026-05-01", "2026-05-01", "East India", "Bihar", "Bodh Gaya", 24.696, 84.987, "buddha_purnima",
      "The full-moon day commemorating the Buddha's birth, enlightenment and parinirvana — butter lamps and chanting fill Bodh Gaya, Sarnath and Himalayan monasteries.",
      "The thrice-blessed day (Vesak) of the Buddhist world, marked by prayer, charity and release of caged birds.",
      "Bodh Gaya's Mahabodhi temple marks the very spot of enlightenment.",
      "Circumambulation of the Mahabodhi tree, sutra chanting, alms-giving, kheer offerings recalling Sujata's gift.",
      ["Butter-lamp offerings", "Bodhi tree circumambulation"],
      ["Kheer"], "Buddhist chanting", "",
      [], [], ["ajanta-caves"]),
    F("moatsu", "Moatsü Festival", "tribal", "2026-05-01", "2026-05-03", "Northeast India", "Nagaland", "Mokokchung", 26.322, 94.522, "hornbill_festival",
      "The post-sowing festival of the Ao Naga tribe — three days of rest, feasting, song and traditional dress after the fields are prepared.",
      "A community blessing of the sown fields, invoking prosperity before the growing season.",
      "An age-old Ao agricultural rite, now centred at Mokokchung.",
      "Sangpangtu bonfires, folk songs, rice-beer sharing, best-attire displays.",
      ["Sangpangtu fire gathering"], ["Smoked pork", "Rice beer (traditional)"], "Ao folk song", "War and harvest dances",
      [], [], [], "verified", "https://nagaland.gov.in"),
    F("ambubachi-mela", "Ambubachi Mela", "religious", "2026-06-22", "2026-06-26", "Northeast India", "Assam", "Guwahati", 26.166, 91.705, "ambubachi_mela",
      "The great tantric fair of Kamakhya temple, when the goddess is believed to undergo her annual cycle and the sanctum closes for three days before a jubilant reopening.",
      "Celebrates the earth's fertility and the divine feminine; lakhs of sadhus and pilgrims camp on Nilachal hill.",
      "Kamakhya is among the oldest Shakti pithas, central to tantric tradition.",
      "Temple closure and reopening rites, distribution of angodak and angabastra prasad.",
      ["Sanctum closure rites", "Sadhu gatherings"], [], "Devotional naam singing", "Deodhani trance dance",
      [], [], []),
    F("hemis-festival", "Hemis Tsechu", "religious", "2026-06-24", "2026-06-25", "Himalayan India", "Ladakh", "Leh", 33.912, 77.700, "hemis_festival",
      "Ladakh's largest monastic festival at Hemis gompa, honouring Guru Padmasambhava with two days of sacred Cham masked dances.",
      "The Cham dances enact the victory of wisdom over ignorance; watching them is held to confer merit.",
      "Hemis monastery, of the Drukpa lineage, was established in 1672.",
      "Masked Cham in the monastery courtyard, giant thangka unfurling every twelve years.",
      ["Cham masked dance", "Thangka display"], ["Butter tea", "Skyu"], "Monastic long horns", "Cham",
      [], [], []),

    # ---------------- JULY ----------------
    F("rath-yatra", "Jagannath Rath Yatra", "religious", "2026-07-16", "2026-07-24", "East India", "Odisha", "Puri", 19.803, 85.818, "rath_yatra",
      "The chariot festival of Puri — Jagannath, Balabhadra and Subhadra ride three colossal wooden chariots pulled by lakhs of devotees down the Grand Road.",
      "The one time the deities leave the sanctum, granting darshan to all regardless of caste or creed; pulling the ropes is held to be liberating.",
      "Recorded for over eight centuries; the English word 'juggernaut' derives from these chariots.",
      "Chhera pahanra royal sweeping, chariot pulling to Gundicha temple, Bahuda return journey.",
      ["New chariots built each year", "Chhera pahanra ritual sweeping"],
      ["Mahaprasad of the temple kitchens", "Poda pitha"], "Odissi sankirtan", "Odissi",
      ["Pahandi procession of the deities"],
      [{"region": "Gujarat", "name": "Ahmedabad Rath Yatra", "note": "The city's grand parallel yatra."},
       {"region": "West Bengal", "name": "Mahesh Rath Yatra", "note": "Bengal's oldest chariot festival (1396)."}],
      ["konark-sun-temple"]),
    F("bonalu", "Bonalu", "religious", "2026-07-19", "2026-08-09", "South India", "Telangana", "Hyderabad", 17.385, 78.456, "bonalu",
      "Telangana's Ashada-month thanksgiving to Mahakali — women carry decorated Bonam pots of jaggery rice on their heads to the goddess's temples on successive Sundays.",
      "An offering of gratitude for the goddess's protection from epidemics, beginning at Golconda fort and moving through Secunderabad and Old City.",
      "Traced to an 1813 plague vow at Ujjaini Mahankali temple, Secunderabad.",
      "Bonam processions, Pothuraju whip dances, Rangam oracle prophecy, Ghatam immersion.",
      ["Bonam pot offering", "Pothuraju dance", "Rangam prophecy"],
      ["Bonam jaggery rice"], "Teen maar drums", "Pothuraju and folk dance",
      [], [], ["telugu-language", "biryani-hyderabadi"]),
    F("ashadhi-ekadashi", "Ashadhi Ekadashi & Pandharpur Wari", "religious", "2026-07-24", "2026-07-24", "West India", "Maharashtra", "Solapur (Pandharpur)", 17.679, 75.331, "ashadhi_ekadashi",
      "The culmination of the Pandharpur Wari — lakhs of Warkari pilgrims walk for weeks with the padukas of Dnyaneshwar and Tukaram to stand before Vitthal.",
      "An 800-year-old walking tradition of radical equality, song and devotion at the heart of Marathi bhakti culture.",
      "The Wari predates even Dnyaneshwar (13th c.), whose palkhi joined it later.",
      "Dindi processions with cymbals and mridang, ringan circular formations, midnight darshan.",
      ["Palkhi processions", "Ringan formations"],
      ["Vrat fasting foods"], "Abhang bhajans", "Dindi fugdi steps",
      [], [], []),
    F("guru-purnima", "Guru Purnima", "religious", "2026-07-29", "2026-07-29", "Pan-India", "Pan-India", None, 25.282, 82.956, "guru_purnima",
      "The full moon of the teacher — students across traditions honour their gurus, from classical music gharanas to monasteries and ashrams.",
      "Dedicated to sage Vyasa; in Indian tradition the guru is the lamp that transmits knowledge across generations.",
      "Also Vyasa Purnima; the Buddha gave his first sermon at Sarnath on this day.",
      "Paduka puja, offerings to teachers, special recitals by disciples.",
      ["Guru paduka puja", "Gurudakshina offerings"], [], "Guru vandana recitals", "",
      [], [], ["carnatic-music", "tabla"]),
    F("kharchi-puja", "Kharchi Puja", "tribal", "2026-07-23", "2026-07-29", "Northeast India", "Tripura", "Agartala", 23.831, 91.286, "temple_festival_generic",
      "Tripura's week-long royal festival worshipping the fourteen dynastic deities at Old Agartala, blending tribal and Hindu tradition.",
      "A purification of the earth after Ama Pechi, uniting Tripuri tribes and the former royal house.",
      "Continued by the Manikya dynasty's royal priests, the Chantais.",
      "Bathing of the fourteen deities in the Saidra river, sacrifices, week-long fair.",
      ["Fourteen-deity procession"], [], "Tribal drums and flutes", "Hozagiri glimpses",
      [], [], [], "verified", "https://tripuratourism.gov.in"),

    # ---------------- AUGUST ----------------
    F("independence-day-culture", "Independence Day Cultural Celebrations", "national", "2026-08-15", "2026-08-15", "Pan-India", "Delhi", "New Delhi", 28.656, 77.241, "republic_day",
      "India's Independence Day — the tricolour rises over the Red Fort and cultural programmes, kite flying and patriotic song fill the country.",
      "Commemorates freedom at midnight, 15 August 1947; Delhi's skies traditionally fill with kites.",
      "The Prime Minister has addressed the nation from the Red Fort since 1947.",
      "Flag hoisting, school cultural programmes, kite flying in Old Delhi.",
      ["Red Fort address", "Kite flying"], [], "Patriotic song", "", [], [], ["red-fort"]),
    F("onam", "Onam", "harvest", "2026-08-15", "2026-08-26", "South India", "Kerala", "Thiruvananthapuram", 8.524, 76.936, "onam",
      "Kerala's ten-day harvest festival welcoming King Mahabali home — pookalam flower carpets grow daily until Thiruvonam's grand sadya feast.",
      "Celebrates an egalitarian golden age under Mahabali; a secular festival embraced by all Malayali communities.",
      "Traced to Sangam-era harvest celebrations of Chingam.",
      "Pookalam laying, Onasadya on banana leaf, Vallam Kali snake-boat races, Pulikali tiger dances, Kaikottikali.",
      ["Pookalam flower carpets", "Vallam Kali boat races", "Pulikali tiger dance", "Onakkodi new clothes"],
      ["Onasadya (26+ dishes)", "Payasam", "Avial", "Sharkara varatti"], "Vanchipattu boat songs", "Thiruvathirakali, Kaikottikali",
      ["Thrikkakara appan installation"],
      [{"region": "Alappuzha", "name": "Nehru Trophy Vallam Kali", "note": "The premier snake-boat race on Punnamada lake."}],
      ["onam", "kathakali", "malabar-spices"]),
    F("raksha-bandhan", "Raksha Bandhan", "cultural", "2026-08-28", "2026-08-28", "North & West India", "Pan-India", None, 28.613, 77.209, "raksha_bandhan",
      "The festival of the protective thread — sisters tie rakhis on brothers' wrists, renewing a bond of care sealed with sweets and gifts.",
      "The rakhi is a prayer for the brother's long life and his vow of protection; historically it also forged alliances beyond kinship.",
      "Legends range from Draupadi and Krishna to Rani Karnavati's rakhi to Humayun.",
      "Rakhi tying with tilak and aarti, gift exchange, family gatherings.",
      ["Rakhi tying", "Aarti thali"], ["Ghewar", "Ladoo", "Barfi"], "", "",
      [], [{"region": "Coastal West", "name": "Narali Purnima", "note": "Coconut offerings to the sea by fishing communities."}],
      []),

    # ---------------- SEPTEMBER ----------------
    F("janmashtami", "Krishna Janmashtami", "religious", "2026-09-04", "2026-09-05", "Pan-India", "Uttar Pradesh", "Mathura", 27.505, 77.672, "janmashtami",
      "The midnight birth of Krishna — temples in Mathura-Vrindavan overflow, while Maharashtra's govinda teams build human pyramids to smash the dahi handi.",
      "Krishna's birth in a prison cell at midnight is re-enacted with jhankis, fasting and song across India.",
      "Mathura and Vrindavan have celebrated Krishna's birthplace traditions for two millennia.",
      "Midnight abhisheka, jhulan cradle ceremonies, dahi handi pyramids, raslila.",
      ["Dahi handi pyramids", "Midnight birth aarti", "Jhanki tableaux"],
      ["Makhan-mishri", "Panjiri", "Chappan bhog"], "Krishna bhajans, haveli sangeet", "Raslila",
      ["Fasting till midnight"],
      [{"region": "Maharashtra", "name": "Dahi Handi", "note": "Govinda pathaks compete on Mumbai streets."},
       {"region": "Gujarat", "name": "Makhan chor processions", "note": "Dwarka temple celebrations."}],
      []),
    F("ganesh-chaturthi", "Ganesh Chaturthi", "religious", "2026-09-14", "2026-09-25", "West & South India", "Maharashtra", "Mumbai", 18.982, 72.833, "ganesh_chaturthi",
      "Eleven days when Maharashtra breathes with Ganpati — clay idols installed in homes and giant mandals, ending in seas of devotees at visarjan processions.",
      "Ganesha, remover of obstacles, is welcomed as a beloved guest; Tilak transformed the festival into a public movement of unity in 1893.",
      "Peshwa-era household worship made public during the freedom struggle.",
      "Pranapratishtha installation, daily aarti, modak offerings, dhol-tasha visarjan processions to the sea.",
      ["Sarvajanik mandals", "Dhol-tasha pathaks", "Eco-clay idols", "Visarjan immersion"],
      ["Ukdiche modak", "Puran poli", "Karanji"], "Aarti and dhol-tasha", "Lezim",
      ["Pranapratishtha", "Uttarpuja before immersion"],
      [{"region": "Telangana", "name": "Khairatabad Ganesh", "note": "One of India's tallest idols in Hyderabad."},
       {"region": "Goa", "name": "Chavath", "note": "Home-centred matoli canopy tradition."}],
      ["warli-art"]),
    F("nuakhai", "Nuakhai", "harvest", "2026-09-15", "2026-09-15", "East India", "Odisha", "Sambalpur", 21.470, 83.974, "nuakhai",
      "Western Odisha's new-rice festival — the season's first grains are offered to Maa Samaleswari before families share the nabanna meal together.",
      "Nuakhai Juhar greetings dissolve quarrels; eating the new rice binds family and village in gratitude.",
      "An ancient agrarian rite formalised under the Chauhan kings of Sambalpur.",
      "First-grain offering at an auspicious lagna, family feasts, Sambalpuri folk dance evenings.",
      ["Nabanna first-grain offering", "Nuakhai Juhar greetings"],
      ["Nua rice dishes", "Manda pitha"], "Sambalpuri folk song", "Rasarkeli & Dalkhai",
      [], [], []),
    F("ziro-festival", "Ziro Festival of Music", "cultural", "2026-09-24", "2026-09-27", "Northeast India", "Arunachal Pradesh", "Lower Subansiri (Ziro)", 27.633, 93.830, "ziro_music",
      "India's greatest outdoor indie music festival, hosted by the Apatani tribe amid the rice terraces of Ziro valley.",
      "A model of community-run cultural tourism where contemporary music meets Apatani heritage in a UNESCO-tentative cultural landscape.",
      "Founded in 2012 by Bobby Hano and Menwhopause's Anup Kutty.",
      "Four days of live stages, bamboo architecture, local food and homestays.",
      ["Bamboo festival architecture", "Apatani hospitality"], ["Apatani platters", "Bamboo-shoot dishes"], "Indie, folk and world music", "",
      [], [], [], "verified", "https://zirofestival.com"),

    # ---------------- OCTOBER ----------------
    F("navratri", "Sharad Navratri", "religious", "2026-10-11", "2026-10-19", "Pan-India", "Gujarat", "Ahmedabad", 23.023, 72.571, "navratri_garba",
      "Nine nights of the Goddess — Gujarat dances garba around the sacred lamp, while the rest of India worships the nine forms of Durga.",
      "Each night honours a form of Shakti; the circular garba mirrors the cycle of creation around the divine flame.",
      "Rooted in Puranic Devi worship; Gujarat's garba tradition is now UNESCO-listed intangible heritage.",
      "Ghatasthapana, nightly garba and dandiya raas, kanya pujan on Ashtami.",
      ["Garba around the garbo lamp", "Dandiya raas", "Golu doll displays in the south"],
      ["Vrat foods: sabudana, kuttu", "Sundal"], "Garba songs, Devi stuti", "Garba & Dandiya",
      ["Ghatasthapana", "Kanya pujan"],
      [{"region": "Tamil Nadu / Karnataka", "name": "Golu / Gombe Habba", "note": "Tiered doll displays and visiting."},
       {"region": "West Bengal", "name": "Durga Puja", "note": "The goddess arrives in sculpted pandals."}],
      []),
    F("durga-puja", "Durga Puja", "religious", "2026-10-16", "2026-10-20", "East India", "West Bengal", "Kolkata", 22.572, 88.363, "durga_puja",
      "Bengal's supreme festival — five days when Kolkata becomes an open-air art gallery of pandals housing the ten-armed goddess, ending in tearful immersions.",
      "Durga's annual homecoming with her children; UNESCO inscribed Kolkata's Durga Puja as Intangible Cultural Heritage in 2021.",
      "Community (barowari) pujas began in 1790 at Guptipara; zamindari pujas earlier still.",
      "Pandal hopping, dhak drumming, dhunuchi naach, Sindoor khela, bhashan immersion.",
      ["Artist-designed pandals", "Dhunuchi naach", "Sindoor khela", "Kumartuli idol craft"],
      ["Bhog khichuri", "Kosha mangsho", "Mishti"], "Dhak drums, agomoni songs", "Dhunuchi dance",
      ["Bodhon awakening", "Sandhi puja"],
      [{"region": "Varanasi/Bihar", "name": "Durga Puja of the east Gangetic belt", "note": "Shared pandal traditions."}],
      ["madhubani", "banarasi-silk"]),
    F("dussehra", "Dussehra (Vijayadashami)", "religious", "2026-10-20", "2026-10-20", "Pan-India", "Delhi", "New Delhi", 28.613, 77.209, "dussehra_ravana",
      "The day of victory — Ramlila grounds across northern India burn towering effigies of Ravana as Rama's triumph of good over evil.",
      "Marks both Rama's victory over Ravana and Durga's over Mahishasura; new ventures and shastra puja are begun today.",
      "Ramlila performance traditions, inscribed by UNESCO, stretch back to Tulsidas's era.",
      "Ramlila theatre, effigy burning, shastra and Saraswati puja, shami leaf exchange.",
      ["Ravana effigy dahan", "Ramlila theatre", "Ayudha puja of tools"],
      ["Jalebi-fafda (Gujarat)", "Sondesh"], "Ramlila mandali music", "Ramlila enactments",
      ["Aparajita puja"],
      [{"region": "Karnataka", "name": "Mysuru Dasara", "note": "Royal Jamboo Savari procession."},
       {"region": "Himachal Pradesh", "name": "Kullu Dussehra", "note": "Week-long gathering of valley deities."},
       {"region": "Chhattisgarh", "name": "Bastar Dussehra", "note": "75-day tribal chariot festival."},
       {"region": "West Bengal", "name": "Bijoya Dashami", "note": "Durga's immersion and sindoor khela."}],
      ["dussehra"]),
    F("mysuru-dasara", "Mysuru Dasara", "religious", "2026-10-11", "2026-10-20", "South India", "Karnataka", "Mysuru", 12.305, 76.655, "mysuru_dasara",
      "Karnataka's Nada Habba — ten days when Mysore Palace glows with a hundred thousand bulbs, ending in the Jamboo Savari elephant procession bearing Chamundeshwari's golden howdah.",
      "A 400-year royal continuation of the Vijayanagara Mahanavami, celebrating the goddess Chamundeshwari's victory.",
      "Begun by Raja Wodeyar I in 1610 at Srirangapatna, inheriting Vijayanagara court ritual described by foreign travellers at Hampi.",
      "Palace illumination, durbar rituals, cultural concerts, Jamboo Savari and torchlight parade.",
      ["Jamboo Savari golden howdah", "Palace illumination", "Torchlight parade"],
      ["Mysore pak"], "Palace band and classical concerts", "Classical and folk showcases",
      ["Chamundi Hill puja"], [], ["hampi", "hampi-virupaksha"], "verified", "https://mysoredasara.gov.in"),
    F("kullu-dussehra", "Kullu Dussehra", "religious", "2026-10-20", "2026-10-26", "North India", "Himachal Pradesh", "Kullu", 31.958, 77.109, "kullu_dussehra",
      "The Himalayan Dussehra that begins when the plains finish — over 200 village deities travel in palanquins to Dhalpur maidan to honour Raghunath ji for a week.",
      "A living assembly of Himachal's devta tradition, recognised as an international festival; no effigies are burnt here.",
      "Instituted in 1660 by Raja Jagat Singh in penance to Lord Raghunath.",
      "Deity processions with narsingha trumpets, Raghunath's chariot pulling, Lanka dahan by the Beas.",
      ["Devta palanquin assembly", "Chariot procession"],
      ["Himachali dham feast"], "Narsingha and karnal horns", "Nati folk dance",
      [], [], ["dussehra"]),
    F("bastar-dussehra", "Bastar Dussehra", "tribal", "2026-08-13", "2026-10-23", "Central India", "Chhattisgarh", "Bastar (Jagdalpur)", 19.081, 82.030, "bastar_dussehra",
      "The world's longest festival — 75 days of tribal rites in Bastar honouring Devi Danteshwari, crowned by a massive hand-built chariot pulled by hundreds of villagers.",
      "Not about Rama at all: an indigenous goddess festival where Muria, Maria, Bhatra and Halba tribes each hold hereditary ritual roles.",
      "Begun by Maharaja Purushottam Deo in the 15th century.",
      "Pata jatra log worship, kachan gadi throne rites, eight-wheeled rath circumambulation, muria durbar.",
      ["Hand-carved wooden rath", "Kachan Gadi rites", "Muria Durbar"],
      ["Bastar tribal cuisine"], "Tribal drums, mohri", "Tribal dances of Bastar",
      [], [], ["dussehra"]),
    F("bathukamma", "Bathukamma", "cultural", "2026-10-10", "2026-10-18", "South India", "Telangana", "Hyderabad", 17.385, 78.486, "bathukamma",
      "Telangana's flower festival — women build luminous conical stacks of gunuka and tangedu blooms, circle them singing folk songs, then float them on water.",
      "A celebration of womanhood and Telangana's ecology; the state's signature cultural identity festival.",
      "An ancient folk goddess tradition, elevated to state festival in 2014.",
      "Daily bathukamma stacking through nine days, evening circle songs, Saddula Bathukamma immersion.",
      ["Flower stack arranging", "Circle folk singing", "Water immersion"],
      ["Maleeda", "Satthu pindi"], "Bathukamma folk songs", "Circular clap dance",
      [], [], ["telugu-language"]),

    # ---------------- NOVEMBER ----------------
    F("diwali", "Diwali (Deepavali)", "religious", "2026-11-06", "2026-11-10", "Pan-India", "Uttar Pradesh", "Varanasi", 25.317, 82.973, "diwali",
      "The festival of lights — five days from Dhanteras to Bhai Dooj when every threshold glows with diyas, rangoli and the worship of Lakshmi.",
      "Light's victory over darkness: Rama's return to Ayodhya, Krishna's defeat of Narakasura, and Lakshmi's blessing of homes.",
      "Deepotsava traditions are described from the Skanda Purana onward; Jains mark Mahavira's nirvana, Sikhs the Bandi Chhor Divas.",
      "Diya lighting, Lakshmi-Ganesh puja on Amavasya (8 Nov), rangoli, fireworks, sweets and gifting.",
      ["Diya rows and rangoli", "Lakshmi puja", "Annakut on Govardhan day"],
      ["Ladoo", "Kaju katli", "Chakli", "Karanji"], "Aarti and shehnai", "",
      ["Dhanteras metal buying", "Lakshmi puja at pradosh"],
      [{"region": "South India", "name": "Naraka Chaturdashi", "note": "Pre-dawn oil bath as the main day (7 Nov)."},
       {"region": "Bengal", "name": "Kali Puja", "note": "The goddess Kali worshipped on the new moon."},
       {"region": "Punjab", "name": "Bandi Chhor Divas", "note": "Golden Temple illuminated for Guru Hargobind's release."}],
      ["diwali", "banarasi-silk"]),
    F("govardhan-puja", "Govardhan Puja (Annakut)", "religious", "2026-11-09", "2026-11-09", "North India", "Uttar Pradesh", "Mathura", 27.492, 77.673, "govardhan_annakut",
      "The day after Diwali's new moon, when temples raise mountains of food — the Annakut — recalling Krishna lifting Govardhan hill to shelter Braj.",
      "Teaches reverence for nature over pride: Krishna redirected worship from Indra to the hill that sustains the cowherds.",
      "Central to Pushtimarg and Braj temple tradition for centuries.",
      "Annakut food mountains, Govardhan parikrama, gobar hill effigies, cattle decoration.",
      ["Annakut chappan bhog", "Govardhan parikrama"],
      ["Annakut sabzi", "Kadhi-chawal"], "Haveli sangeet", "",
      [], [], []),
    F("bhai-dooj", "Bhai Dooj", "cultural", "2026-11-11", "2026-11-11", "North India", "Pan-India", None, 28.613, 77.209, "bhai_dooj",
      "The closing day of the Diwali cycle — sisters apply tilak to brothers, praying for their long life, mirroring Yamuna's welcome of Yama.",
      "Completes Diwali with the celebration of the sibling bond, echoing Raksha Bandhan.",
      "Rooted in the Yama-Yamuna legend of the Puranas.",
      "Tilak ceremony, feasts at the sister's home, gift exchange.",
      ["Tilak and aarti of brothers"], ["Basundi", "Kheer"], "", "",
      [], [{"region": "Maharashtra", "name": "Bhau Beej", "note": "Marathi observance."},
           {"region": "Bengal", "name": "Bhai Phonta", "note": "Sandalwood phonta with conch blowing."}],
      []),
    F("chhath-puja", "Chhath Puja", "religious", "2026-11-13", "2026-11-16", "East India", "Bihar", "Patna", 25.612, 85.144, "chhath_puja",
      "Bihar's most sacred festival — four days of rigorous fasting ending with arghya to the setting and rising sun, offered waist-deep in rivers.",
      "A Vedic-rooted sun worship with no idols or priests, led largely by women (vratis), thanking Surya and Chhathi Maiya for life itself.",
      "Held to descend from Vedic surya upasana; sung in Bhojpuri and Maithili folk tradition.",
      "Nahay-khay purification, kharna, sandhya arghya at dusk, usha arghya at dawn.",
      ["36-hour nirjala fast", "River ghat arghya", "Soop and daura baskets"],
      ["Thekua", "Rasiao kheer", "Seasonal fruit"], "Chhath geet folk songs", "",
      ["Sandhya and Usha arghya"], [], []),
    F("guru-nanak-gurpurab", "Guru Nanak Gurpurab", "religious", "2026-11-24", "2026-11-24", "North India", "Punjab", "Amritsar", 31.620, 74.876, "guru_nanak_gurpurab",
      "The birth anniversary of Guru Nanak Dev Ji — the Golden Temple blazes with lights and fireworks as nagar kirtans and akhand paths fill Punjab.",
      "Honours the founder of Sikhism and his message of Ik Onkar — one creator, equality and seva.",
      "Guru Nanak was born in 1469 at Rai Bhoi di Talwandi (Nankana Sahib).",
      "48-hour Akhand Path, Prabhat Pheri hymns, nagar kirtan with Panj Pyare, langar for all.",
      ["Akhand Path", "Nagar kirtan", "Langar seva"],
      ["Kada prasad", "Langar meals"], "Shabad kirtan", "Gatka martial display",
      [], [], []),
    F("pushkar-mela", "Pushkar Camel Fair", "cultural", "2026-11-18", "2026-11-24", "North India", "Rajasthan", "Ajmer (Pushkar)", 26.489, 74.551, "pushkar_fair",
      "Rajasthan's legendary Kartik fair — tens of thousands of camels and horses traded on the dunes beside the sacred Pushkar lake, ending in Kartik Purnima dips.",
      "A rare fusion of livestock economy and pilgrimage at one of the world's only Brahma temples.",
      "Centuries old, tied to Kartik Purnima bathing at Pushkar's 52 ghats.",
      "Camel decoration contests, folk performances, hot-air balloons, Purnima snan.",
      ["Camel trading and races", "Kartik Purnima snan"],
      ["Dal baati churma", "Malpua"], "Rajasthani manganiyar music", "Kalbelia",
      [], [], ["kalbelia-dance", "amber-fort", "usta-kala"]),
    F("hampi-utsav", "Hampi Utsav (Vijaya Utsav)", "cultural", "2026-11-06", "2026-11-08", "South India", "Karnataka", "Vijayanagara (Hampi)", 15.335, 76.462, "temple_festival_generic",
      "Karnataka's heritage festival amid the ruins of Vijayanagara — dance, music, light shows and processions restore Hampi's imperial festivities.",
      "Echoes the legendary Mahanavami celebrations of the Vijayanagara empire described by Persian and Portuguese travellers.",
      "Held by Karnataka's government since 1987; dates announced annually.",
      "Stages across the boulderscape, jumbo savari, light-and-sound shows.",
      ["Heritage-site concerts"], [], "Classical and folk concerts", "Folk dance ensembles",
      [], [], ["hampi", "hampi-virupaksha", "yakshagana"], "tentative", "https://karnatakatourism.org"),

    # ---------------- DECEMBER ----------------
    F("hornbill-festival", "Hornbill Festival", "tribal", "2026-12-01", "2026-12-10", "Northeast India", "Nagaland", "Kohima (Kisama)", 25.647, 94.117, "hornbill_festival",
      "The 'Festival of Festivals' — all major Naga tribes gather at Kisama heritage village for ten days of dance, log drums, indigenous games and morung culture.",
      "A deliberate act of cultural preservation, showcasing the distinct heritage of 17+ Naga tribes to the world.",
      "Instituted by Nagaland in 2000, named for the revered hornbill of Naga folklore.",
      "Tribal dance arenas, Naga chilli-eating contests, rock concerts, craft bazaars.",
      ["Morung exhibitions", "Log drum performances", "Naga wrestling"],
      ["Smoked pork with axone", "Naga king chilli dishes"], "Naga folk fusion & rock", "War dances of the tribes",
      [], [], [], "verified", "https://hornbillfestival.com"),
    F("christmas-india", "Christmas — Indian Traditions", "religious", "2026-12-24", "2026-12-25", "Pan-India", "Goa", "Old Goa", 15.503, 73.911, "christmas_goa",
      "Christmas the Indian way — Goa's baroque churches glow with paper-star lanterns and midnight mass, Kerala lights up, and hill stations carol through winter.",
      "India's Christian communities, from Goan Catholics to Nagaland's churches, blend local culture with the Nativity.",
      "Christianity in India dates to St Thomas (1st c. CE); Goa's churches are UNESCO heritage.",
      "Midnight mass, star lanterns, cribs (presepio), kuswar sweet platters, carol singing.",
      ["Paper-star lanterns", "Nativity cribs", "Carol rounds"],
      ["Kuswar sweets", "Bebinca", "Plum cake", "Kerala achappam"], "Carols and Konkani mandos", "",
      [], [{"region": "Kerala", "name": "Christmas-Buon Natale", "note": "Thrissur's massive carol processions."},
           {"region": "Meghalaya/Nagaland", "name": "Hill Christmas", "note": "Community feasts and choirs."}],
      []),
    F("losar-monpa", "Losar of the Monpas (Torgya)", "religious", "2026-01-30", "2026-02-01", "Northeast India", "Arunachal Pradesh", "Tawang", 27.586, 91.859, "losar",
      "Tawang monastery's Torgya festival — Monpa masked dances exorcise evil and pray for prosperity in the high Himalaya.",
      "A Monpa Buddhist purification festival distinct from, and adjacent to, the Losar new year cycle.",
      "Performed annually at Tawang, India's largest monastery, founded 1680.",
      "Sacred Cham in the monastery courtyard over three days.",
      ["Torgya Cham dances"], ["Zan and butter tea"], "Monastic ritual music", "Cham",
      [], [], [], "verified", "https://arunachaltourism.com"),
]
