"""Seed data for Virana heritage records. Loaded on backend startup if collection is empty."""

HERITAGE_SEED = [
    {
        "id": "taj-mahal",
        "name": "Taj Mahal",
        "category": "monuments",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "lat": 27.1751,
        "lng": 78.0421,
        "era": "1632-1653 CE",
        "dynasty": "Mughal Empire",
        "builder": "Shah Jahan",
        "short": "An ivory-white marble mausoleum on the south bank of the Yamuna, built by Emperor Shah Jahan in memory of Mumtaz Mahal.",
        "history": "Commissioned in 1632 by Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal, the Taj Mahal took over two decades to complete. Master craftsman Ustad Ahmad Lahauri is generally considered the principal designer. Over 20,000 artisans, calligraphers, stone-carvers and inlay workers laboured on this monument. Its perfect symmetry, pietra dura inlay and Persian-inspired charbagh garden layout are considered the apogee of Mughal architecture.",
        "significance": "UNESCO World Heritage Site (1983). A universal symbol of love and one of the New Seven Wonders of the World.",
        "architecture": "White Makrana marble; onion dome flanked by four minarets; pietra dura inlays of jasper, jade, turquoise, lapis lazuli. Perfect bilateral symmetry with the exception of the two cenotaphs.",
        "image": "https://images.unsplash.com/photo-1526711657229-e7e080ed7aa1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "red-fort",
        "name": "Red Fort (Lal Qila)",
        "category": "monuments",
        "state": "Delhi",
        "district": "Delhi",
        "lat": 28.6562,
        "lng": 77.2410,
        "era": "1639-1648 CE",
        "dynasty": "Mughal Empire",
        "builder": "Shah Jahan",
        "short": "Massive red sandstone fortress that served as the main residence of Mughal emperors for nearly 200 years.",
        "history": "Built when Shah Jahan moved his capital from Agra to Shahjahanabad (Old Delhi). Chief architect Ustad Ahmad Lahauri. The Prime Minister of India hoists the national flag here every Independence Day.",
        "significance": "UNESCO World Heritage Site (2007). Symbol of India's independence and Mughal architectural excellence.",
        "architecture": "Red sandstone walls stretching 2.4 km, Diwan-i-Aam (Hall of Public Audience), Diwan-i-Khas (Hall of Private Audience) inlaid with precious stones.",
        "image": "https://images.unsplash.com/photo-1587474260584-136574528ed5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "hampi",
        "name": "Hampi Ruins",
        "category": "monuments",
        "state": "Karnataka",
        "district": "Vijayanagara",
        "lat": 15.3350,
        "lng": 76.4600,
        "era": "1336-1565 CE",
        "dynasty": "Vijayanagara Empire",
        "builder": "Harihara I & successors",
        "short": "Ruins of the once-glorious capital of the Vijayanagara Empire, a UNESCO World Heritage Site of over 1,600 surviving structures.",
        "history": "At its peak in the 16th century, Hampi was the second-largest medieval city in the world after Beijing. Portuguese and Persian travelers described its bazaars overflowing with pearls, rubies and silk. The city fell to a coalition of Deccan sultanates at the Battle of Talikota in 1565.",
        "significance": "UNESCO World Heritage Site (1986). Preserves the finest example of Dravidian temple architecture and Vijayanagara urban planning.",
        "architecture": "Virupaksha Temple, Vittala Temple's stone chariot, musical pillars, aqueducts, royal enclosure. Boulders of the Deccan plateau integrated into the design.",
        "image": "https://images.unsplash.com/photo-1600100397774-4a5da1e9c1b3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "konark-sun-temple",
        "name": "Konark Sun Temple",
        "category": "temples",
        "state": "Odisha",
        "district": "Puri",
        "lat": 19.8876,
        "lng": 86.0945,
        "era": "13th century CE",
        "dynasty": "Eastern Ganga Dynasty",
        "builder": "King Narasimhadeva I",
        "short": "13th-century Sun Temple designed as a colossal chariot of the Sun God Surya, with 24 intricately carved wheels.",
        "history": "Built by King Narasimhadeva I of the Eastern Ganga dynasty. The 24 wheels of the chariot function as sundials, precisely tracking time by the shadow of the axle. The main sanctuary collapsed over centuries — theories range from a lightning strike to structural failure of the corbelled roof.",
        "significance": "UNESCO World Heritage Site (1984). Called the 'Black Pagoda' by European sailors who used its silhouette as a navigational marker.",
        "architecture": "Kalinga architecture; 12 pairs of wheels; seven galloping horses; erotic sculptures and celestial dancers.",
        "image": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "ajanta-caves",
        "name": "Ajanta Caves",
        "category": "monuments",
        "state": "Maharashtra",
        "district": "Aurangabad",
        "lat": 20.5519,
        "lng": 75.7033,
        "era": "2nd century BCE - 6th century CE",
        "dynasty": "Satavahana, Vakataka",
        "builder": "Buddhist monastic communities",
        "short": "30 rock-cut Buddhist cave monuments containing some of the finest surviving murals of ancient India.",
        "history": "Carved into a horseshoe-shaped cliff along the Waghora river. Rediscovered in 1819 by British officer John Smith during a tiger hunt. Depicts Jataka tales — stories of the Buddha's previous lives.",
        "significance": "UNESCO World Heritage Site (1983). Masterpieces of Buddhist religious art.",
        "architecture": "Chaityas (prayer halls) and viharas (monasteries) carved from a single basalt cliff. Frescoes made from natural pigments still vivid after 1,500 years.",
        "image": "https://images.unsplash.com/photo-1580500550469-4a2ed3f6a4b6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "meenakshi-temple",
        "name": "Meenakshi Amman Temple",
        "category": "temples",
        "state": "Tamil Nadu",
        "district": "Madurai",
        "lat": 9.9195,
        "lng": 78.1194,
        "era": "6th century CE (current structure ~17th century)",
        "dynasty": "Pandya / Nayak",
        "builder": "Vishwanatha Nayak",
        "short": "Iconic Dravidian temple dedicated to Meenakshi (Parvati) and Sundareshwarar (Shiva), with 14 gopurams towering up to 52 metres.",
        "history": "Originally built around the 6th century, the current structure was rebuilt by Vishwanatha Nayak in the 17th century after Muslim invasions. The temple has 14 gopurams (gateway towers), the tallest of which is 52 meters tall, covered with over 33,000 sculptures.",
        "significance": "Nominee for the New Seven Wonders. One of India's most visited temples and a Paadal Petra Sthalam.",
        "architecture": "Dravidian style; Hall of Thousand Pillars (Aayiram Kaal Mandapam); Golden Lotus Tank.",
        "image": "https://images.unsplash.com/photo-1585506942812-e72b29cef752?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "kuchipudi",
        "name": "Kuchipudi",
        "category": "dance",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "lat": 16.4667,
        "lng": 80.9500,
        "era": "3rd century BCE (formalized 17th century)",
        "dynasty": None,
        "builder": "Siddhendra Yogi (formalizer, 17th c.)",
        "short": "Classical dance form from Andhra Pradesh combining rapid rhythmic footwork, expressive eyes, and dramatic storytelling.",
        "history": "Named after the village of Kuchelapuram (Kuchipudi) in Krishna district. Formalized by Siddhendra Yogi in the 17th century. Originally performed only by male Brahmin dancers who narrated devotional Vaishnavite stories.",
        "significance": "One of the eight officially recognized Indian classical dances. Recognized by Sangeet Natak Akademi.",
        "architecture": "Uses tarangam (dancing on the rim of a brass plate) and stories from Bhagavata Purana. Costume uses handloom silk sarees, temple jewelry, and ghungroo bells.",
        "image": "https://images.unsplash.com/photo-1756370256926-e48ca54c5efe?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "kathakali",
        "name": "Kathakali",
        "category": "dance",
        "state": "Kerala",
        "district": "Thrissur",
        "lat": 10.5276,
        "lng": 76.2144,
        "era": "17th century CE",
        "dynasty": None,
        "builder": "Zamorin of Calicut & Kottarakkara Thampuran",
        "short": "Elaborate classical dance-drama of Kerala with colorful facial makeup, giant costumes, and codified gestural language.",
        "history": "Emerged in the 17th century from earlier temple performing arts like Krishnanattam and Ramanattam. Dancers train from childhood, especially in Netra Bhedam — the practice of expressive eye movements sometimes trained for years.",
        "significance": "One of India's eight classical dance forms. UNESCO recognized as intangible cultural heritage indirectly through Koodiyattam lineage.",
        "architecture": "Chutti (facial makeup) applied for hours; pacha (green) for heroes, kathi (knife) for villains. Stories from Ramayana and Mahabharata.",
        "image": "https://images.unsplash.com/photo-1715181751269-2c8325468b73?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "bharatanatyam",
        "name": "Bharatanatyam",
        "category": "dance",
        "state": "Tamil Nadu",
        "district": "Thanjavur",
        "lat": 10.7870,
        "lng": 79.1378,
        "era": "1000 BCE - present",
        "dynasty": "Chola influenced",
        "builder": "Temple devadasi tradition",
        "short": "One of the oldest classical dance forms of India, characterized by fixed upper torso, bent legs, and intricate hand mudras.",
        "history": "Rooted in Bharata Muni's Natya Shastra (~200 BCE). Preserved for centuries by devadasis (temple dancers). Revived in the 20th century by Rukmini Devi Arundale.",
        "significance": "Considered the mother of all Indian classical dances. Performed globally as a symbol of Indian classical heritage.",
        "architecture": "Aramandi (half-sitting posture); nine rasas (emotions); accompanied by Carnatic music, mridangam and nattuvangam.",
        "image": "https://images.unsplash.com/photo-1583211082022-9b2f36c1a8c3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "dussehra",
        "name": "Dussehra (Vijayadashami)",
        "category": "festivals",
        "state": "Pan-India",
        "district": None,
        "lat": 22.5726,
        "lng": 88.3639,
        "era": "Ancient",
        "dynasty": None,
        "builder": None,
        "short": "Ten-day festival celebrating the victory of good over evil — Rama over Ravana, or Durga over Mahishasura.",
        "history": "Mentioned in the Ramayana and Devi Mahatmya. Celebrated with regional variations: Mysore Dasara royal procession, Kolkata Durga Puja immersions, North Indian Ram Lila enactments culminating in burning effigies of Ravana.",
        "significance": "One of India's most important festivals; marks the end of Navratri and the beginning of preparations for Diwali.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1604608672516-b56f7c0eeb4a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "diwali",
        "name": "Diwali (Deepavali)",
        "category": "festivals",
        "state": "Pan-India",
        "district": None,
        "lat": 28.6139,
        "lng": 77.2090,
        "era": "Ancient",
        "dynasty": None,
        "builder": None,
        "short": "Festival of Lights celebrating the return of Rama to Ayodhya, and honoring Lakshmi, goddess of wealth.",
        "history": "Rooted in multiple traditions — Rama's return from 14-year exile, Krishna's defeat of Narakasura, and the enlightenment of Mahavira. Celebrated across South Asia by Hindus, Jains, Sikhs and Buddhists.",
        "significance": "The most widely celebrated Indian festival worldwide. National holiday in India and several other countries.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1605116959589-14d0d2c8d3c1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "onam",
        "name": "Onam",
        "category": "festivals",
        "state": "Kerala",
        "district": None,
        "lat": 10.8505,
        "lng": 76.2711,
        "era": "Ancient",
        "dynasty": None,
        "builder": None,
        "short": "Kerala's harvest festival celebrating the annual visit of King Mahabali, marked by pookalam flower carpets and Vallam Kali boat races.",
        "history": "Celebrates the mythical King Mahabali, a benevolent asura ruler who is said to visit Kerala every year during Onam. Traditions include the Onam Sadhya (26-dish feast on banana leaf), Pulikali tiger dance, and snake boat races on the backwaters.",
        "significance": "Kerala's state festival and its most inclusive celebration cutting across religion.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1596363505729-4190a9506133?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "tabla",
        "name": "Tabla",
        "category": "instruments",
        "state": "Pan-India (North)",
        "district": None,
        "lat": 26.8467,
        "lng": 80.9462,
        "era": "13th century CE",
        "dynasty": "Delhi Sultanate origins",
        "builder": "Amir Khusrau (traditional attribution)",
        "short": "Pair of hand-drums — the small dayan and the larger bayan — foundational to Hindustani classical music.",
        "history": "Traditionally traced to Amir Khusrau in the 13th century, though the modern tabla likely evolved in the 18th century. Six major gharanas (schools) exist: Delhi, Ajrada, Lucknow, Farrukhabad, Banaras and Punjab.",
        "significance": "The most prominent percussion instrument of Hindustani music. Global icon through masters like Ustad Zakir Hussain.",
        "architecture": "Dayan carved from wood; bayan from clay, brass or copper. Both heads made from goat skin with syahi (black paste) for tonal control.",
        "image": "https://images.unsplash.com/photo-1519683384663-1e1e93b5b1c9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "sitar",
        "name": "Sitar",
        "category": "instruments",
        "state": "Pan-India (North)",
        "district": None,
        "lat": 25.3176,
        "lng": 82.9739,
        "era": "13th-18th century evolution",
        "dynasty": None,
        "builder": "Amir Khusrau (traditional)",
        "short": "Long-necked plucked string instrument central to Hindustani classical music.",
        "history": "Evolved from the ancient veena, influenced by Persian setar. Popularized worldwide by Pt. Ravi Shankar in the 1960s, notably through his association with The Beatles.",
        "significance": "Global ambassador of Indian classical music. Featured on the UNESCO list of musical instruments of intangible heritage.",
        "architecture": "Long teak neck; 18-21 strings including sympathetic strings (tarab); resonating gourd (tumba); movable frets.",
        "image": "https://images.unsplash.com/photo-1546874177-9e664107314e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "biryani-hyderabadi",
        "name": "Hyderabadi Biryani",
        "category": "food",
        "state": "Telangana",
        "district": "Hyderabad",
        "lat": 17.3850,
        "lng": 78.4867,
        "era": "17th century",
        "dynasty": "Nizams of Hyderabad",
        "builder": None,
        "short": "Aromatic slow-cooked layered rice dish with marinated meat, saffron, and Deccan spices — a jewel of Nizami cuisine.",
        "history": "Evolved in the royal kitchens of the Nizams of Hyderabad, blending Mughal and Telugu culinary traditions. The dum pukht (slow-cooking sealed) technique traps aroma and moisture.",
        "significance": "GI-tag protected. Arguably India's most famous rice dish, with regional variants from Kolkata to Kerala.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1563379091339-03246963d51a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "malabar-spices",
        "name": "Malabar Spice Heritage",
        "category": "spices",
        "state": "Kerala",
        "district": "Kozhikode",
        "lat": 11.2588,
        "lng": 75.7804,
        "era": "3000 BCE - present",
        "dynasty": "Zamorin trade",
        "builder": None,
        "short": "Kerala's ancient spice coast — the cradle of the global spice trade in black pepper, cardamom and cinnamon.",
        "history": "The Malabar Coast has traded spices with Sumerians, Egyptians, Greeks, Romans, Chinese and eventually the Portuguese since 3000 BCE. The 1498 arrival of Vasco da Gama triggered the European age of exploration and colonization.",
        "significance": "GI-tag protected Malabar Pepper. UNESCO-recognized spice heritage.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1546702005-7f8e5aeab4a6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "pashmina",
        "name": "Kashmiri Pashmina",
        "category": "crafts",
        "state": "Jammu & Kashmir",
        "district": "Srinagar",
        "lat": 34.0837,
        "lng": 74.7973,
        "era": "15th century",
        "dynasty": "Sultan Zain-ul-Abidin patronage",
        "builder": None,
        "short": "The world's finest handwoven wool, spun from the underfur of Changthangi goats of Ladakh's high plateau.",
        "history": "Introduced to Kashmir by Sultan Zain-ul-Abidin in the 15th century. A single Pashmina shawl can take up to two years to hand-spin and weave. Marco Polo wrote about it.",
        "significance": "GI-tag protected. UNESCO-recognized as a living cultural craft.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1591903881161-054c73b7b7fa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "madhubani",
        "name": "Madhubani Painting",
        "category": "crafts",
        "state": "Bihar",
        "district": "Madhubani",
        "lat": 26.3527,
        "lng": 86.0713,
        "era": "Ancient (Ramayana era, per tradition)",
        "dynasty": None,
        "builder": "Village women of Mithila",
        "short": "Ritual folk paintings from the Mithila region — bold linework, natural pigments, and geometric floral motifs.",
        "history": "Traditionally painted on the walls of homes by women during weddings and festivals. Discovered by the outside world in 1934 when a British officer surveyed earthquake damage. GI-tag received in 2007.",
        "significance": "GI-tag protected. Preserves oral religious narratives through visual storytelling.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1583211092518-b6d0e0e8b8a1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "telugu-language",
        "name": "Telugu Language",
        "category": "languages",
        "state": "Andhra Pradesh / Telangana",
        "district": None,
        "lat": 16.5062,
        "lng": 80.6480,
        "era": "1st millennium BCE - present",
        "dynasty": "Satavahana, Chalukya, Kakatiya, Vijayanagara",
        "builder": None,
        "short": "Classical Dravidian language spoken by 96 million+ people — often called 'Italian of the East' for its melodic vowels.",
        "history": "Earliest inscriptions date from the 6th century BCE. Received Classical Language status from the Government of India in 2008. Rich literary tradition including Nannaya's Andhra Mahabharatam.",
        "significance": "Third most-spoken native language in India. Fourth most-spoken language in India after Hindi, Bengali, Marathi.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1568205563075-77f9b1a80f9e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "great-andamanese",
        "name": "Great Andamanese Languages",
        "category": "languages",
        "state": "Andaman & Nicobar Islands",
        "district": "Strait Island",
        "lat": 12.5300,
        "lng": 92.9400,
        "era": "70,000+ years",
        "dynasty": None,
        "builder": None,
        "short": "One of the world's most endangered language families — fewer than 5 fluent speakers of remaining dialects remain.",
        "history": "Once ten distinct languages spoken by different Great Andamanese tribes. Population devastated by British colonial contact and epidemics. Linguist Anvita Abbi has led documentation efforts.",
        "significance": "Believed to represent one of humanity's oldest surviving language families, possibly descended from the first out-of-Africa migration.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "hampi-virupaksha",
        "name": "Virupaksha Temple, Hampi",
        "category": "temples",
        "state": "Karnataka",
        "district": "Vijayanagara",
        "lat": 15.3350,
        "lng": 76.4600,
        "era": "7th century CE",
        "dynasty": "Chalukya - Vijayanagara",
        "builder": "Various patrons",
        "short": "Continuously functioning temple within Hampi's ruins, dedicated to Shiva as Virupaksha since at least the 7th century.",
        "history": "The oldest continuously functioning temple in India and predates the founding of Vijayanagara. Its 50-meter gopuram is a landmark of Hampi.",
        "significance": "Part of UNESCO Hampi complex. Living temple with unbroken worship for over 1,300 years.",
        "architecture": "Nine-tiered eastern gopuram, ranga mandapa with murals, and a pinhole camera projection of the gopuram inside the temple.",
        "image": "https://images.unsplash.com/photo-1602940659805-770d1b3b9911?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "amber-fort",
        "name": "Amer (Amber) Fort",
        "category": "monuments",
        "state": "Rajasthan",
        "district": "Jaipur",
        "lat": 26.9855,
        "lng": 75.8513,
        "era": "1592 CE",
        "dynasty": "Kachwaha Rajput",
        "builder": "Raja Man Singh I",
        "short": "Hilltop Rajput fortress-palace in pink sandstone and white marble overlooking Maota Lake.",
        "history": "Founded by Raja Man Singh I, a general in Akbar's army. Expanded over centuries by Jai Singh I and Sawai Jai Singh II. Sheesh Mahal (Mirror Palace) inside is inlaid with thousands of tiny mirrors.",
        "significance": "UNESCO World Heritage Site (Hill Forts of Rajasthan, 2013).",
        "architecture": "Blends Rajput and Mughal styles. Diwan-i-Aam, Ganesh Pol, Sheesh Mahal, and cool underground tunnel to Jaigarh Fort.",
        "image": "https://images.unsplash.com/photo-1477587458883-47145ed94245?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "khajuraho",
        "name": "Khajuraho Group of Monuments",
        "category": "temples",
        "state": "Madhya Pradesh",
        "district": "Chhatarpur",
        "lat": 24.8318,
        "lng": 79.9199,
        "era": "950-1050 CE",
        "dynasty": "Chandela",
        "builder": "Chandela kings",
        "short": "Nagara-style Hindu and Jain temples renowned for their intricate erotic and celestial sculptures.",
        "history": "Originally 85 temples; only 25 survive. Built by the Chandela dynasty across a century. Rediscovered by T.S. Burt in 1838.",
        "significance": "UNESCO World Heritage Site (1986). Represents the artistic pinnacle of medieval North Indian temple architecture.",
        "architecture": "Nagara style with shikharas (spires). Kandariya Mahadev is the largest. Sculptures depict deities, dancers, musicians and mithuna scenes.",
        "image": "https://images.unsplash.com/photo-1592635196078-c1b17a83b3d5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "warli-art",
        "name": "Warli Painting",
        "category": "crafts",
        "state": "Maharashtra",
        "district": "Palghar",
        "lat": 19.6969,
        "lng": 72.7692,
        "era": "3000 BCE - present",
        "dynasty": None,
        "builder": "Warli tribal community",
        "short": "Tribal mural art of the Warli people, using stark white pigment on ochre mud walls to depict daily life and rituals.",
        "history": "One of the oldest surviving folk art forms of India, tracing back to the neolithic period. Uses only circles, triangles and squares. Central motif is the Tarpa dance around a musician.",
        "significance": "GI-tag protected. Documents an ancient tribal worldview.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1610030006760-3ed08fdb51b9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "usta-kala",
        "name": "Usta Kala (Bikaner Gold Art)",
        "category": "crafts",
        "state": "Rajasthan",
        "district": "Bikaner",
        "lat": 28.0229,
        "lng": 73.3119,
        "era": "16th century",
        "dynasty": "Bikaner royal patronage",
        "builder": "Usta master families",
        "short": "Endangered craft of miniature gold-on-camel-leather painting, practiced today by only a handful of families.",
        "history": "Brought to Bikaner from Persia in the 16th century. Uses 24-karat gold leaf on lacquered camel-hide. Only about 8 master families remain, making this one of India's most critically endangered crafts.",
        "significance": "GI-tag protected. Considered critically endangered by traditional craft protection agencies.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1597423244036-ef5020e83f3c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "holi",
        "name": "Holi",
        "category": "festivals",
        "state": "Pan-India",
        "district": None,
        "lat": 27.4924,
        "lng": 77.6737,
        "era": "Ancient",
        "dynasty": None,
        "builder": None,
        "short": "Festival of colors marking the arrival of spring, the victory of good over evil, and the divine love of Radha and Krishna.",
        "history": "Rooted in the story of Prahlada and the demoness Holika. Also celebrates Krishna's playful color-throwing with Radha and the gopis of Vrindavan. Famous Lathmar Holi at Barsana.",
        "significance": "One of India's most joyous festivals. Celebrated globally by the Indian diaspora.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1615461066841-6116e61058f4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "yakshagana",
        "name": "Yakshagana",
        "category": "dance",
        "state": "Karnataka",
        "district": "Udupi",
        "lat": 13.3409,
        "lng": 74.7421,
        "era": "16th century CE",
        "dynasty": None,
        "builder": "Coastal Karnataka villages",
        "short": "Vibrant folk theatre of coastal Karnataka combining dance, music, dialogue, and elaborate face paint.",
        "history": "Emerged in the 16th century in the temple town of Udupi. All-night performances of mythological stories from the epics.",
        "significance": "Represents Karnataka's most iconic folk performing art.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1600891964092-4316c288032e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "kakinada-kaja",
        "name": "Kakinada Kaja",
        "category": "food",
        "state": "Andhra Pradesh",
        "district": "Kakinada",
        "lat": 16.9891,
        "lng": 82.2475,
        "era": "19th century",
        "dynasty": None,
        "builder": None,
        "short": "GI-tag protected sweet from Kakinada — golden layered pastry rolls soaked in sugar syrup.",
        "history": "A speciality of Kakinada in coastal Andhra Pradesh. GI-tag received in 2020 to protect its authentic recipe.",
        "significance": "GI-tag protected. Central to Andhra weddings and festivals.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "toda-embroidery",
        "name": "Toda Embroidery (Pukhoor)",
        "category": "crafts",
        "state": "Tamil Nadu",
        "district": "Nilgiris",
        "lat": 11.4064,
        "lng": 76.6932,
        "era": "Ancient",
        "dynasty": None,
        "builder": "Toda pastoral community",
        "short": "Distinctive red-and-black geometric embroidery of the Toda tribe of the Nilgiris, done without any embroidery frame.",
        "history": "Practiced by Toda women without any tracing or frame — designs are counted stitch by stitch on plain white cloth. GI-tag received in 2013.",
        "significance": "GI-tag protected. Central to Toda ritual life; used in the puthukuli shawl.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1610030006760-3ed08fdb51b9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "carnatic-music",
        "name": "Carnatic Music",
        "category": "music",
        "state": "South India",
        "district": None,
        "lat": 13.0827,
        "lng": 80.2707,
        "era": "13th century CE (systematized)",
        "dynasty": None,
        "builder": "Purandara Dasa (father of Carnatic music)",
        "short": "South Indian classical music tradition centered on devotional composition, structured ragas and complex talas.",
        "history": "Systematized by Purandara Dasa (1484-1564). The 'Trinity of Carnatic Music' — Tyagaraja, Muthuswami Dikshitar, Shyama Shastri — composed thousands of krithis in the 18th-19th centuries.",
        "significance": "One of two main classical music traditions of India. Celebrated annually in the Madras Music Season (December).",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1519683384663-1e1e93b5b1c9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
    {
        "id": "kalbelia-dance",
        "name": "Kalbelia Dance",
        "category": "dance",
        "state": "Rajasthan",
        "district": "Pushkar",
        "lat": 26.4899,
        "lng": 74.5511,
        "era": "Ancient",
        "dynasty": None,
        "builder": "Kalbelia serpent-charmer community",
        "short": "Sinuous dance of the Kalbelia snake charmers of Rajasthan — inscribed on UNESCO's Intangible Heritage list.",
        "history": "Traditionally performed by women of the Kalbelia community, whose men are snake charmers. Movements imitate the serpent.",
        "significance": "UNESCO Representative List of the Intangible Cultural Heritage of Humanity (2010).",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1583211082022-9b2f36c1a8c3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "kavu-groves",
        "name": "Kavu Sacred Groves",
        "category": "rituals",
        "state": "Kerala",
        "district": "Various",
        "lat": 10.8505,
        "lng": 76.2711,
        "era": "Ancient",
        "dynasty": None,
        "builder": None,
        "short": "Sacred forest sanctuaries of Kerala, protected by local communities as abodes of serpent deities and forest spirits.",
        "history": "Small forest patches preserved through religious taboos for centuries — many hundreds still exist in Kerala. Rich biodiversity hotspots featuring rare medicinal plants.",
        "significance": "Recognized as community biodiversity reserves; disappearing as urbanization spreads.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "AT_RISK",
    },
    {
        "id": "banarasi-silk",
        "name": "Banarasi Silk",
        "category": "crafts",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "lat": 25.3176,
        "lng": 82.9739,
        "era": "Mughal-era refinement",
        "dynasty": "Mughal patronage",
        "builder": "Weavers of Banaras",
        "short": "Handwoven silk saree of Varanasi with intricate Mughal-inspired zari brocade, made on pit looms over weeks.",
        "history": "Refined under Mughal patronage in the 14th-16th centuries. A single Banarasi saree can take 15 days to six months on a pit loom.",
        "significance": "GI-tag protected. Considered essential for North Indian brides.",
        "architecture": None,
        "image": "https://images.unsplash.com/photo-1591903881161-054c73b7b7fa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "status": "verified",
        "preservation": "ACTIVE",
    },
]

STATES = [
    {"code": "AP", "name": "Andhra Pradesh", "lat": 15.9129, "lng": 79.7400},
    {"code": "TS", "name": "Telangana", "lat": 17.1232, "lng": 79.2088},
    {"code": "KA", "name": "Karnataka", "lat": 15.3173, "lng": 75.7139},
    {"code": "KL", "name": "Kerala", "lat": 10.8505, "lng": 76.2711},
    {"code": "TN", "name": "Tamil Nadu", "lat": 11.1271, "lng": 78.6569},
    {"code": "MH", "name": "Maharashtra", "lat": 19.7515, "lng": 75.7139},
    {"code": "RJ", "name": "Rajasthan", "lat": 27.0238, "lng": 74.2179},
    {"code": "DL", "name": "Delhi", "lat": 28.7041, "lng": 77.1025},
    {"code": "UP", "name": "Uttar Pradesh", "lat": 26.8467, "lng": 80.9462},
    {"code": "MP", "name": "Madhya Pradesh", "lat": 22.9734, "lng": 78.6569},
    {"code": "OR", "name": "Odisha", "lat": 20.9517, "lng": 85.0985},
    {"code": "WB", "name": "West Bengal", "lat": 22.9868, "lng": 87.8550},
    {"code": "GJ", "name": "Gujarat", "lat": 22.2587, "lng": 71.1924},
    {"code": "BR", "name": "Bihar", "lat": 25.0961, "lng": 85.3131},
    {"code": "PB", "name": "Punjab", "lat": 31.1471, "lng": 75.3412},
    {"code": "JK", "name": "Jammu & Kashmir", "lat": 33.7782, "lng": 76.5762},
    {"code": "AN", "name": "Andaman & Nicobar Islands", "lat": 11.7401, "lng": 92.6586},
]

CATEGORIES = [
    {"id": "monuments", "name": "Monuments & Forts", "color": "#F56A1E", "icon": "Landmark"},
    {"id": "temples", "name": "Sacred Temples", "color": "#E89B17", "icon": "Sun"},
    {"id": "dance", "name": "Classical & Folk Dance", "color": "#C85A32", "icon": "Sparkles"},
    {"id": "music", "name": "Music & Ragas", "color": "#2B3A67", "icon": "Music"},
    {"id": "instruments", "name": "Rare Instruments", "color": "#3B5998", "icon": "Music2"},
    {"id": "food", "name": "Culinary Heritage", "color": "#B8433E", "icon": "Utensils"},
    {"id": "spices", "name": "Spices & Ayurveda", "color": "#8B4513", "icon": "Leaf"},
    {"id": "crafts", "name": "Handicrafts & Textiles", "color": "#1B7A56", "icon": "Scissors"},
    {"id": "languages", "name": "Languages & Dialects", "color": "#6E4C9E", "icon": "Languages"},
    {"id": "festivals", "name": "Festivals", "color": "#D4368A", "icon": "Calendar"},
    {"id": "rituals", "name": "Rituals & Oral Tales", "color": "#7A6C48", "icon": "BookOpen"},
    {"id": "at_risk", "name": "Heritage at Risk", "color": "#DC2626", "icon": "AlertTriangle"},
]
